import { type GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { LeagueComboBox } from "~/components/league-combobox";
import { SeasonComboBox } from "~/components/season-combobox";
import { columns } from "~/components/table/columns";
import { DataTable } from "~/components/table/data-table";
import { Skeleton } from "~/components/ui/skeleton";
import { api } from "~/utils/api";

type SeasonProps = {
  leagueId: string;
  season: string;
};

const useStandings = ({ leagueId, season }: SeasonProps) => {
  const data = api.standings.getStandings.useQuery({
    leagueId: leagueId,
    season: season,
  });
  return { ...data };
};
const useLeagues = () => api.leagues.getLeagues.useQuery();
const useSeasons = (season: SeasonProps["season"]) => {
  return api.seasons.getSeasons.useQuery({ leagueId: season });
};

export default function Season(params: SeasonProps) {
  const standings = useStandings(params);
  const leagues = useLeagues();
  const seasons = useSeasons(params.leagueId);
  const currentSeasonImg = leagues.data?.comboData.find(
    (league) => league.id === params.leagueId,
  )?.img_url;
  return (
    <>
      <Head>
        <title>Footy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className="min-h-screen bg-background p-4 sm:p-8">
        <div className="mx-auto w-full max-w-5xl px-2">
          <div className="flex items-start justify-between">
            <div className="flex items-center space-x-5">
              <div className="space-y-1">
                <span className="block font-semibold text-muted-foreground">
                  League:
                </span>
                {leagues.isLoading ? (
                  <>
                    <Skeleton className="h-[40px] w-[400px] rounded-full" />
                  </>
                ) : (
                  <LeagueComboBox leagues={leagues.data?.comboData ?? []} />
                )}
              </div>
              <div className="space-y-1">
                <span className="block font-semibold text-muted-foreground">
                  Season:
                </span>
                {seasons.isLoading ? (
                  <>
                    <Skeleton className="h-[40px] w-[200px] rounded-full" />
                  </>
                ) : (
                  <SeasonComboBox seasons={seasons.data?.comboData ?? []} />
                )}
              </div>
            </div>
            <div>
              {currentSeasonImg ? (
                <Image
                  className="rounded-lg"
                  width={80}
                  height={80}
                  alt="Current season image"
                  src={currentSeasonImg}
                  priority
                />
              ) : null}
            </div>
          </div>
          <div className="mt-3">
            {standings.isLoading ? (
              <div className="space-y-5">
                {Array.from({ length: 20 }).map(
                  (_, idx): JSX.Element => (
                    <div key={idx} className="flex items-center space-x-3">
                      <Skeleton className="h-[13px] w-full rounded-full" />
                    </div>
                  ),
                )}
              </div>
            ) : (
              <DataTable columns={columns} data={standings.data?.rows ?? []} />
            )}
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { leagueId, season } = context.query;
  return {
    props: {
      leagueId: leagueId ?? "2023-2024",
      season: season,
    },
  };
};
