import Head from "next/head";
import Image from "next/image";
import { useState, useEffect, type FormEvent } from "react";
import { columns } from "~/components/table/columns";
import { DataTable } from "~/components/table/data-table";
import { Button } from "~/components/ui/button";
import { Label } from "~/components/ui/label";
import { RadioGroup, RadioGroupItem } from "~/components/ui/radio-group";
import { type StandingColumn } from "~/shared/types";
import { api } from "~/utils/api";

const useSelectedLeague = () => {
  const [selectedLeague, setSelectedLeague] = useState<{
    name: string;
    id: `${string}.${number}` | "";
  }>({
    name: "",
    id: "",
  });
  const standings = api.standings.getStandings.useQuery();
  const leagues = api.leagues.getLeagues.useQuery();
  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const data = Object.fromEntries(formData);
    // if (typeof league === "string") {
    //   setSelectedLeague({
    //     name: league,
    //     id: "",
    //   });
    // }
  };

  return { selectedLeague, standings, leagues, handleSubmit };
};

export default function Home() {
  const { selectedLeague, standings, leagues, handleSubmit } =
    useSelectedLeague();
  const tableData = api.standings.getTableInfo.useQuery();
  if (standings.isLoading || tableData.isLoading) return <div>Loading...</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-background p-8 text-foreground">
        <div className="flex grid-cols-2 gap-4 pt-6 sm:gap-2">
          <form className="w-full max-w-sm" onSubmit={handleSubmit}>
            <h1 className="text-2xl font-bold">{standings.data?.data.name}</h1>
            {/* TODO: DEFAULT LEAGUE */}
            <RadioGroup name="league" className="mt-4 flex flex-col ">
              {leagues.data?.data.map((league) => (
                <div
                  key={league.id}
                  className="flex items-center space-x-2 text-base"
                >
                  <RadioGroupItem value={league.id} id={league.name} />
                  <Label
                    className="py-1 text-base font-normal text-muted-foreground"
                    htmlFor={league.name}
                  >
                    {league.name}
                  </Label>
                </div>
              ))}
            </RadioGroup>
            <Button className="mt-4 w-full max-w-xs" variant="default">
              Submit
            </Button>
          </form>
          <div className="">
            {selectedLeague
              ? (() => {
                  const rows = tableData.data?.rows ?? [];
                  return <DataTable columns={columns} data={rows} />;
                })()
              : null}
          </div>
        </div>
      </main>
    </>
  );
}
